Build the release process

diff --git a/run b/run
--- a/run
+++ b/run
@@ -212,6 +212,83 @@ run_rmdb() {
    rm -f config/local/vplan/server/db/*.sqlite
 }
 
+# Release a specific version and tag the code
+run_release() {
+   if [ $# != 1 ]; then
+      echo "run release <version>"
+      exit 1
+   fi
+
+   VERSION=$(echo "$1" | sed 's/^v//') # so you can use "0.1.5 or "v0.1.5"
+   COPYRIGHT="$(date +'%Y')"
+   DATE=$(date +'%d %b %Y')
+   TAG="v$VERSION" # follow PEP 440 naming convention
+   FILES="NOTICE pyproject.toml Changelog"
+   MESSAGE="Release v$VERSION"
+
+   if [ "$(git branch -a | grep '^\*' | sed 's/^\* //')" != "master" ]; then
+      echo "*** You are not on master; you cannot release from this branch"
+      exit 1
+   fi
+
+   git tag -l "$TAG" | grep -q "$TAG"
+   if [ $? = 0 ]; then
+      echo "*** Version v$VERSION already tagged"
+      exit 1
+   fi
+
+   head -1 Changelog | grep -q "^Version $VERSION\s\s*unreleased"
+   if [ $? != 0 ]; then
+      echo "*** Unreleased version v$VERSION is not at the head of the Changelog"
+      exit 1
+   fi
+
+   poetry version $VERSION
+   if [ $? != 0 ]; then
+      echo "*** Failed to update version"
+      exit 1
+   fi
+
+   sed -i "s/^Version $VERSION\s\s*unreleased/Version $VERSION     $DATE/g" Changelog
+   sed -i -E "s/(^ *Copyright \(c\) *)([0-9,-]+)( *Kenneth.*$)/\1$COPYRIGHT\3/" NOTICE
+
+   git diff $FILES
+
+   git commit --no-verify -m "$MESSAGE" $FILES
+   if [ $? != 0 ]; then
+      echo "*** Commit step failed"
+      exit 1
+   fi
+
+   git tag -a "$TAG" -m "$MESSAGE"
+   if [ $? != 0 ]; then
+      echo "*** Tag step failed"
+      exit 1
+   fi
+
+   rm -f dist/*
+
+   poetry build
+   if [ $? != 0 ]; then
+      echo "*** Build step failed."
+      exit 1
+   fi
+
+   tar zcf dist/vplan-config-$VERSION.tar.gz \
+       -C config/installed --mode="go-rwx" --owner=github --group=github .
+   if [ $? != 0 ]; then
+      echo "*** Config bundle step failed."
+      exit 1
+   fi
+
+   echo ""
+   echo "*** Version v$VERSION has been released and committed"
+   echo "*** You may push now: git push --follow-tags"
+   echo "*** Don't forget to attach build artifacts::"
+   ls -l dist
+   echo ""
+}
+
 # Execute one of the developer tasks
 case $1 in
    install|setup)
@@ -269,6 +346,13 @@ case $1 in
    rmdb)
       run_rmdb
       ;;
+   release)
+      shift 1
+      run_release $*
+      ;;
+   build)
+      run_build
+      ;;
    *)
       echo ""
       echo "------------------------------------"
@@ -289,6 +373,8 @@ case $1 in
       echo "- run server -r: Run the vplan REST server, removing the database first"
       echo "- run vplan: Run the vplan client against localhost:8080"
       echo "- run rmdb: Remove the sqlite database files used for local testing"
+      echo "- run release: Release a specific version and tag the code"
+      echo "- run build: Build artifacts and push the released tag to GitHub"
       echo ""
       exit 1
 esac
